site_name: Objektovo Orientované Programovanie
site_url: https://oop.wagjo.com
plugins:
  - glightbox:
      manual: true
nav:
  - Úvod: 'index.md'
  - Teória: 
    - 1 - Úvod a motivácia: 'teoria-3/t01-uvod.md'
    - 2 - Algoritmus, dátové typy a premenné: 'teoria-3/t02-typy.md'
    - 3 - Identita, objekt: 'teoria-3/t03-objekt.md'
    - 4 - Trieda, balíky: 'teoria-3/t04-trieda.md'
    - 5 - Výnimky: 'teoria-3/t05-vynimky.md'    
    - 6 - Operátory: 'teoria-3/t06-operatory.md'    
    - 7 - Metódy: 'teoria-3/t07-metody.md'    
    - 8 - Inicializácia objektov: 'teoria-3/t08-konstruktor.md'
    - 9 - Premenné a atribúty: 'teoria-3/t09-premenne.md'
    - 10 - Zapuzdrenie: 'teoria-3/t10-zapuzdrenie.md'
    - 11 - Dedičnosť: 'teoria-3/t11-dedicnost.md'
    - 12 - Polymorfizmus: 'teoria-3/t12-polymorfizmus.md'
    - 13 - Abstrakcia: 'teoria-3/t13-abstrakcia.md'
    - 14 - Enumeračné typy: 'teoria-3/t14-enum.md'
  - Cvičenia: 
    - 1 - Úvod, vývojový diagram: 'cvicenie-3/c01-uvod.md'
    - 2 - Prvý Java program: 'cvicenie-3/c02-hello.md'
    - 3 - Riadenie toku programu: 'cvicenie-3/c03-cykly.md'
    - 4 - Polia, varargs: 'cvicenie-3/c04-polia.md'
    - 5 - Obalené typy: 'cvicenie-3/c05-wrapper.md'
    - 6 - Reťazce znakov: 'cvicenie-3/c06-stringy.md'
    - 7 - Triedy a metódy: 'cvicenie-3/c07-triedy.md'
    - 8 - Hangman: 'cvicenie-3/c08-metody.md'
    - 9 - Slovník: 'cvicenie-3/c09-konstruktor.md'
    - 10 - Dedičnosť: 'cvicenie-3/c10-dedicnost.md'
  - Pokročilí: 
    - 1 - Úvod, premenné, vstup a výstup: 'pokrocili-3/p01-uvod.md'
    - 2 - Vetvenie, cykly: 'pokrocili-3/p02-cykly.md'
    - 3 - Rekurzia: 'pokrocili-3/p03-rekurzia.md'
    - 4 - Moduly: 'pokrocili-3/p04-moduly.md'
    - 5 - Správa knižníc: 'pokrocili-3/p05-pip.md'
    - 6 - Agilný vývoj: 'pokrocili-3/p06-agile.md'
    - 7 - Git: 'pokrocili-3/p07-git.md'
    - 8 - GitHub: 'pokrocili-3/p08-github.md'
    - 9 - Trieda a metódy: 'pokrocili-3/p09-oop.md'
    - 10 - Metódy a JSON: 'pokrocili-3/p10-metody.md'
    - 11 - Zapuzdrenie: 'pokrocili-3/p11-zapuzdrenie.md'
    - 12 - Dedičnosť: 'pokrocili-3/p12-dedicnost.md'
    - 13 - Pygame: 'pokrocili-3/p13-pygame.md'
    #- 14 - Pygame 2: 'pokrocili-3/p14-pygame-mys.md'
  - Prehľad tém: 'prehlad.md'
  - Zbierka úloh: 
    - Java - Dedičnosť: 'zbierka-java/j05-04-dedicnost.md'
    - Python - Dedičnosť: 'zbierka-python/j05-04-dedicnost.md'
  #- Ťahák: 'tahak.md'
  - Kontakt: 'autor.md'
copyright: Copyright © 2025, Jozef Wagner. Licencované v rámci <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a>
theme:
  name: material
  features:
    - toc.integrate
    - content.code.copy
    - content.code.annotate
    #- navigation.instant
    - navigation.tracking
    - navigation.top
    - toc.follow
    - navigation.tabs
    - header.autohide
  palette:
    primary: blue grey
extra_css:
  - stylesheets/tufte-sidebars.css
markdown_extensions:
  - attr_list
  - abbr
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys
  - toc:
      permalink: true